In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import time
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
WeatherPy_Database_df = pd.read_csv("Challenge/WeatherPy_Database.csv")
WeatherPy_Database_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description,Rain(Inches),Snow (inches)
0,0,Terney,RU,2020-06-22 01:04:16,45.05,136.61,53.26,93,100,2.48,light rain,0.48,0.0
1,1,Gallipoli,TR,2020-06-22 01:04:16,40.41,26.67,67.50,79,0,5.48,clear sky,0.00,0.0
2,2,Atuona,PF,2020-06-22 01:04:16,-9.80,-139.03,80.11,69,0,10.63,clear sky,0.00,0.0
3,3,Puerto Ayora,EC,2020-06-22 01:04:16,-0.74,-90.35,70.00,94,10,1.01,clear sky,0.00,0.0
4,4,Punta Arenas,CL,2020-06-22 01:04:17,-53.15,-70.92,35.60,93,93,4.70,overcast clouds,0.00,0.0

In [3]:
#Configure gma;s to use your Google API key
gmaps.configure(api_key=g_key)

In [4]:
WeatherPy_Database_df.dtypes

City_ID                  int64
City                    object
Country                 object
Date                    object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Weather Description     object
Rain(Inches)           float64
Snow (inches)          float64
dtype: object

In [5]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip?"))
max_temp = float(input("What is the maximum temperature you would like for your trip?"))

What is the minimum temperature you would like for your trip?75
What is the maximum temperature you would like for your trip?90

In [6]:
rain = (input("Do you want it to be raining? (yes/no) "))

Do you want it to be raining? (yes/no) no

In [7]:
snow = (input("Do you want it to be snowing? (yes/no) "))

Do you want it to be snowing? (yes/no) no

In [8]:
# Filter the dataset to find the cities that fit the criteria.
if rain == "no" and snow == "no":
    preferred_cities_df = WeatherPy_Database_df.loc[(WeatherPy_Database_df["Max Temp"] <= max_temp) & 
                                       (WeatherPy_Database_df["Max Temp"] >= min_temp)& 
                                        (WeatherPy_Database_df["Rain(Inches)"] == 0) & 
                                        (WeatherPy_Database_df["Snow (inches)"] == 0)]
elif rain == "no" and snow =="yes":
    preferred_cities_df = WeatherPy_Database_df.loc[(WeatherPy_Database_df["Max Temp"] <= max_temp) & 
                                       (WeatherPy_Database_df["Max Temp"] >= min_temp)& 
                                        (WeatherPy_Database_df["Rain(Inches)"] == 0) & 
                                        (WeatherPy_Database_df["Snow (inches)"] >= 0)]
elif rain == "yes" and snow == "no":
    preferred_cities_df = WeatherPy_Database_df.loc[(WeatherPy_Database_df["Max Temp"] <= max_temp) & 
                                       (WeatherPy_Database_df["Max Temp"] >= min_temp)& 
                                        (WeatherPy_Database_df["Rain(Inches)"] >= 0) & 
                                        (WeatherPy_Database_df["Snow (inches)"] == 0)]
else:
    preferred_cities_df = WeatherPy_Database_df.loc[(WeatherPy_Database_df["Max Temp"] <= max_temp) & 
                                       (WeatherPy_Database_df["Max Temp"] > min_temp)& 
                                        (WeatherPy_Database_df["Rain(Inches)"] > 0) & 
                                        (WeatherPy_Database_df["Snow (inches)"] > 0)]
    
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description,Rain(Inches),Snow (inches)
2,2,Atuona,PF,2020-06-22 01:04:16,-9.80,-139.03,80.11,69,0,10.63,clear sky,0.0,0.0
7,7,Hithadhoo,MV,2020-06-22 01:04:18,-0.60,73.08,83.70,67,100,5.30,overcast clouds,0.0,0.0
9,9,Maine-Soroa,NE,2020-06-22 01:04:19,13.21,12.02,85.82,48,6,15.37,clear sky,0.0,0.0
10,10,Ambon,ID,2020-06-22 01:04:19,-3.70,128.18,82.40,78,75,5.82,shower rain,0.0,0.0
11,11,Nieuw Amsterdam,SR,2020-06-22 01:04:20,5.88,-55.08,82.40,78,20,9.17,few clouds,0.0,0.0

In [9]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng", "Weather Description"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Weather Description,Hotel Name
2,Atuona,PF,80.11,-9.80,-139.03,clear sky,
7,Hithadhoo,MV,83.70,-0.60,73.08,overcast clouds,
9,Maine-Soroa,NE,85.82,13.21,12.02,clear sky,
10,Ambon,ID,82.40,-3.70,128.18,shower rain,
11,Nieuw Amsterdam,SR,82.40,5.88,-55.08,few clouds,
15,Ayotzintepec,MX,80.40,17.67,-96.13,overcast clouds,
16,Avarua,CK,77.00,-21.21,-159.78,broken clouds,
31,Hirara,JP,86.00,24.80,125.28,broken clouds,
34,Georgetown,MY,82.40,5.41,100.34,few clouds,
35,Hilo,US,84.20,19.73,-155.09,clear sky,

In [10]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [11]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
# Create the output file (CSV).
output_data_file = "Challenge/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [13]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Weather</dt><dd>{Weather Description}</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [14]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
current_weather = hotel_df["Weather Description"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
plt.savefig("Challenge/WeatherPy_vacation_map.png")
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))